### ISSUE TITLE
Renaming keys

### ISSUE THREAD

**Issue by orangemug** [oliverbrooks/hannibal#2]
Suggested API for renaming keys

```
"rename": {
  "foo.bar": "foo.baz"
}
```

`foo.bar` is the path in the object so for example the following

```
{
  foo: {
    bar: 3
  }
}
```

Would end up as

```
{
  foo: {
    baz: 3
  }
}
```

**Comment by oliverbrooks** [comment]
Question whether this should be done without nested keys.

schema

``` js
{
  type: "object",
  schema: {
    fname: {
      type: "string",
      renameTo: "firstName"
    },
    address: {
      type: "object",
      renameTo: "location",
      schema: {
        address1: {
          type: "string",
          renameTo: "street"
        }
      }
    }
  }
}
```

input

``` js
{
  fname: "Peach",
  address: {
    address1: "Peach street"
  }
}
```

output

``` js
{
  firstName: "Peach",
  location: {
    street: "Peach street"
  }
}
```

**Comment by orangemug** [comment]
The above doesn't allow you to move objects between sub objects for example

```
"rename": {
  "foo.bar.baz": "hello"
}
```

In

```
{
  foo: {
    bar: {
      baz: 3
    }
  }
}
```

Out

```
{
  hello: 3
}
```

This might be a little tricky to implement but would provide a nice API, @oliverbrooks thoughts?

**Comment by oliverbrooks** [comment]
@orangemug can see your point. Essentially moving data rather than renaming keys. 

I do wonder if the schema approach is suitable for moving data though. The schema defines what is at that specific part of the input object.

If we add knowledge of deeper objects to the schema it starts to make it less composable.

If the API would look something like 

``` js
{
  type: "object",
  schema: {
    fname: {
      type: "string"
    },
    address: {
      type: "object"
      schema: {
        address1: {
          type: "string"
        }
      }
    }
  },
  move: {
    "fname": "firstName",
    "address.address1": "location.street"
  }
}
```

Then I would argue you could put it through Hannibal and then through an object moving library.

As an aside, the object moving will need to know the structure of the new object being built. Especially if moving from say arrays and objects.

What do you think?

**Comment by orangemug** [comment]
Yeah ok that makes sense, shall we remove renames entirely then? (from the README also). On that note shall we remove the `TODO` from the `README` and add them as issues.

**Comment by orangemug** [comment]
Saying that I guess rename without moving could be useful, shall we wait until we have a use case though?

**Comment by orangemug** [comment]
Closing this for now, we can reopen if we find a usecase
